name: SpeedReader
options:
  bundleIdPrefix: com.speedreader
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"

packages:
  SwiftSoup:
    url: https://github.com/scinfu/SwiftSoup
    from: "2.6.0"

targets:
  SpeedReader:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - SpeedReader
    info:
      path: SpeedReader/Info.plist
      properties:
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true
          UISceneConfigurations: {}
        UILaunchScreen: {}
        UISupportedInterfaceOrientations~iphone:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIBackgroundModes:
          - audio
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.fredriksafsten.speedreader
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_EMIT_LOC_STRINGS: YES
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "Apple Development"
        DEVELOPMENT_TEAM: 5XR7USWXMZ
    dependencies:
      - package: SwiftSoup
